In [70]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso
from sklearn.model_selection import RandomizedSearchCV
df=pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [71]:
df.shape

(768, 9)

In [72]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [73]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [74]:
df["Outcome"].unique()

array([1, 0])

In [75]:
df.isna().sum()




Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [76]:
df["BMI"]=df["BMI"].astype('int')
df


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0              6      148             72             35        0   33   
1              1       85             66             29        0   26   
2              8      183             64              0        0   23   
3              1       89             66             23       94   28   
4              0      137             40             35      168   43   
..           ...      ...            ...            ...      ...  ...   
763           10      101             76             48      180   32   
764            2      122             70             27        0   36   
765            5      121             72             23      112   26   
766            1      126             60              0        0   30   
767            1       93             70             31        0   30   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [77]:
x=df.drop("Outcome",axis="columns").values
x

array([[  6.   , 148.   ,  72.   , ...,  33.   ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.   ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.   ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.   ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.   ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.   ,   0.315,  23.   ]],
      shape=(768, 8))

In [78]:
y=df["Outcome"].values
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [79]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [80]:
import numpy as np

np.set_printoptions(suppress=True)
X_train

array([[  7.   , 150.   ,  78.   , ...,  35.   ,   0.692,  54.   ],
       [  4.   ,  97.   ,  60.   , ...,  28.   ,   0.443,  22.   ],
       [  0.   , 165.   ,  90.   , ...,  52.   ,   0.427,  23.   ],
       ...,
       [  4.   ,  94.   ,  65.   , ...,  24.   ,   0.148,  21.   ],
       [ 11.   ,  85.   ,  74.   , ...,  30.   ,   0.3  ,  35.   ],
       [  5.   , 136.   ,  82.   , ...,   0.   ,   0.64 ,  69.   ]],
      shape=(614, 8))

In [81]:
X_test

array([[  1.   , 199.   ,  76.   , ...,  42.   ,   1.394,  22.   ],
       [  2.   , 107.   ,  74.   , ...,  33.   ,   0.404,  23.   ],
       [  4.   ,  76.   ,  62.   , ...,  34.   ,   0.391,  25.   ],
       ...,
       [  4.   , 142.   ,  86.   , ...,  44.   ,   0.645,  22.   ],
       [  3.   , 116.   ,  74.   , ...,  26.   ,   0.107,  24.   ],
       [  1.   , 107.   ,  72.   , ...,  30.   ,   0.821,  24.   ]],
      shape=(154, 8))

In [82]:
Y_train

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [83]:
Y_test

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [84]:
model=DecisionTreeClassifier()
model.fit(X_train,Y_train)
print(model.predict(X_test))

[1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 0 0 1 0
 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 1
 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0]


In [85]:
print(model.score(X_test,Y_test)*100)

76.62337662337663


In [86]:
print(model.predict([[1,93,70,31,0,30,0.315,23]]))

[0]


In [87]:
print(X_test[1:5])

[[  2.    107.     74.     30.    100.     33.      0.404  23.   ]
 [  4.     76.     62.      0.      0.     34.      0.391  25.   ]
 [  5.    166.     72.     19.    175.     25.      0.587  51.   ]
 [  0.    111.     65.      0.      0.     24.      0.66   31.   ]]


In [88]:
print(model.predict(X_test[1:5]))

[0 0 1 0]


In [89]:
final=cross_val_score(model,x,y,cv=10
                     
                     )
final

array([0.7012987 , 0.71428571, 0.71428571, 0.5974026 , 0.76623377,
       0.72727273, 0.76623377, 0.76623377, 0.68421053, 0.77631579])

In [90]:
final.mean()







np.float64(0.7213773069036227)

In [91]:
d={
    "max_depth":[3,5,10],
    "min_samples_split":[2,5,10]
}


In [92]:
model=DecisionTreeClassifier()
obj=GridSearchCV(param_grid=d,cv=10,return_train_score=False,estimator=model)
obj.fit(X_train,Y_train)
print(obj.predict(X_test))


[1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0
 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 1 0 1 0 0 0 0 1
 1 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 1 0 1 0
 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0 1 0 0 0
 0 1 0 0 0 0]


In [93]:
print(obj.score(X_test,Y_test))

0.7597402597402597


In [94]:
df=pd.DataFrame(obj.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.001393      0.000347         0.000593        0.000203   
1       0.001388      0.000230         0.000592        0.000110   
2       0.001499      0.000171         0.000631        0.000128   
3       0.001794      0.000133         0.000577        0.000112   
4       0.001881      0.000243         0.000567        0.000094   
5       0.001975      0.000174         0.000586        0.000111   
6       0.002177      0.000383         0.000427        0.000073   
7       0.001937      0.000078         0.000374        0.000003   
8       0.001945      0.000110         0.000402        0.000049   

   param_max_depth  param_min_samples_split  \
0                3                        2   
1                3                        5   
2                3                       10   
3                5                        2   
4                5                        5   
5                5                       10   
6               10                        2   
7               10                        5   
8               10                       10   

                                       params  split0_test_score  \
0    {'max_depth': 3, 'min_samples_split': 2}           0.661290   
1    {'max_depth': 3, 'min_samples_split': 5}           0.661290   
2   {'max_depth': 3, 'min_samples_split': 10}           0.661290   
3    {'max_depth': 5, 'min_samples_split': 2}           0.693548   
4    {'max_depth': 5, 'min_samples_split': 5}           0.693548   
5   {'max_depth': 5, 'min_samples_split': 10}           0.725806   
6   {'max_depth': 10, 'min_samples_split': 2}           0.822581   
7   {'max_depth': 10, 'min_samples_split': 5}           0.790323   
8  {'max_depth': 10, 'min_samples_split': 10}           0.758065   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.693548           0.741935           0.790323           0.737705   
1           0.693548           0.741935           0.790323           0.737705   
2           0.693548           0.741935           0.790323           0.737705   
3           0.758065           0.741935           0.741935           0.737705   
4           0.758065           0.741935           0.741935           0.737705   
5           0.741935           0.774194           0.741935           0.737705   
6           0.661290           0.725806           0.758065           0.721311   
7           0.661290           0.677419           0.758065           0.688525   
8           0.677419           0.725806           0.774194           0.754098   

   split5_test_score  split6_test_score  split7_test_score  split8_test_score  \
0           0.655738           0.655738           0.672131           0.770492   
1           0.655738           0.655738           0.672131           0.770492   
2           0.655738           0.655738           0.672131           0.770492   
3           0.721311           0.672131           0.737705           0.721311   
4           0.721311           0.688525           0.737705           0.721311   
5           0.721311           0.688525           0.704918           0.721311   
6           0.786885           0.688525           0.622951           0.672131   
7           0.786885           0.688525           0.606557           0.672131   
8           0.721311           0.655738           0.672131           0.704918   

   split9_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.754098         0.713300        0.048683                6  
1           0.754098         0.713300        0.048683                6  
2           0.754098         0.713300        0.048683                6  
3           0.704918         0.723057        0.024833                3  
4           0.704918         0.724696        0.021769                2  
5           0.704918         0.726256        0.023031                1  
6           0.721311         0.718086        0.

In [95]:
obj.best_score_

np.float64(0.72625594923321)

In [96]:
cols=["param_max_depth","param_min_samples_split","mean_score_time"]
df=pd.DataFrame(obj.cv_results_)[cols]
df

param_max_depth  param_min_samples_split  mean_score_time
0                3                        2         0.000593
1                3                        5         0.000592
2                3                       10         0.000631
3                5                        2         0.000577
4                5                        5         0.000567
5                5                       10         0.000586
6               10                        2         0.000427
7               10                        5         0.000374
8               10                       10         0.000402

In [97]:
obj.best_params_

{'max_depth': 5, 'min_samples_split': 10}

In [98]:
obj.best_score_

np.float64(0.72625594923321)

In [100]:
from sklearn.model_selection import RandomizedSearchCV
model=DecisionTreeClassifier()
obj=RandomizedSearchCV(estimator=model,cv=5,return_train_score=False,param_distributions=d,n_iter=2)
obj.fit(X_train,Y_train)
print(obj.predict(X_test))

[1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0
 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 1 0 1 0 0 0 0 1
 1 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 1 0 1 0
 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0 1 0 0 0
 0 1 0 0 0 0]


In [101]:
obj.best_score_

np.float64(0.7084632813541251)

In [102]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
df=pd.read_csv("gender_submission.csv")
df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [103]:
df.shape

(418, 2)

In [104]:
df.columns

Index(['PassengerId', 'Survived'], dtype='object')

In [105]:
x=df.drop("Survived",axis="columns").values
x

array([[ 892],
       [ 893],
       [ 894],
       [ 895],
       [ 896],
       [ 897],
       [ 898],
       [ 899],
       [ 900],
       [ 901],
       [ 902],
       [ 903],
       [ 904],
       [ 905],
       [ 906],
       [ 907],
       [ 908],
       [ 909],
       [ 910],
       [ 911],
       [ 912],
       [ 913],
       [ 914],
       [ 915],
       [ 916],
       [ 917],
       [ 918],
       [ 919],
       [ 920],
       [ 921],
       [ 922],
       [ 923],
       [ 924],
       [ 925],
       [ 926],
       [ 927],
       [ 928],
       [ 929],
       [ 930],
       [ 931],
       [ 932],
       [ 933],
       [ 934],
       [ 935],
       [ 936],
       [ 937],
       [ 938],
       [ 939],
       [ 940],
       [ 941],
       [ 942],
       [ 943],
       [ 944],
       [ 945],
       [ 946],
       [ 947],
       [ 948],
       [ 949],
       [ 950],
       [ 951],
       [ 952],
       [ 953],
       [ 954],
       [ 955],
       [ 956],
       [ 957],
       [ 9

In [106]:
y=df.Survived.values
y

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [108]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [109]:
model=DecisionTreeClassifier()
model.fit(X_train,Y_train)
print(model.predict(X_test))

[1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 1 0 1 1 0 0
 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0
 0 0 0 1 1 0 1 0 0 0]


In [110]:
print(model.predict([[1309]]))

[0]


In [111]:
print(model.score(X_test,Y_test))

0.5476190476190477


In [112]:
print(model.predict([[896]]))

[0]


In [113]:
final=cross_val_score(model,x,y,cv=5)
final

array([0.35714286, 0.4047619 , 0.46428571, 0.65060241, 0.37349398])